[mypy]
python_version = 3.12
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
ignore_missing_imports = True
follow_imports = skip

[mypy-tests.*]
disallow_untyped_defs = False
warn_return_any = False
ignore_missing_imports = True
